% define_g_dc.m 
%   Define Dream Chaser NPC guidance state structure.
%
% Aeroassist Simulation source code
%
% Developed by:
%   Space Systems Design Lab
%   Daniel Guggenheim School of Aerospace Engineering
%   Georgia Institute of Technology
%
% Inputs:
%   none
%   
% Outputs:
%   g_dc - struct(1), md, guidance data structure
%
% Major Revision History:
%   *Created 3 FEB 2012, Z.R. Putnam

function g_dc = define_g_dc()
%#codegen


%% Parameter data structure
p = struct( ...
    'iter_max', uint8(0), ...
    'mass', double(0), ...
    'h', double(0), ...
    'alt_min', double(0), ...
    'alt_max', double(0), ...
    't_max_ini', double(0), ...
    'p_r', double(0), ...
    'mu', double(0), ...
    'surface_g', double(0), ...
    'omega', double(zeros(3,1)), ...
    'k', double(0), ...
    'nose_radius', double(0), ...
    'area_ref', double(0), ...
    'atm_gamma', double(0), ...
    'atm_R', double(0), ...
    'atm_table', double(zeros(1000,7)), ...
    'vMin', double(0), ...
    'dBank', double(0), ...
    'tolBank', double(0), ...
    'tolRange', double(0), ...
    'caGamma', double(0), ...
    'tgt_lat_geod', double(0), ...
    'tgt_lon_geod', double(0), ...
    'latT', double(0), ...
    'lonT', double(0), ...
    'azi_limit_1', double(0), ...
    'azi_limit_2', double(0), ...
    'azi_limit_3', double(0), ...
    'azi_limit_v1', double(0), ...
    'azi_limit_v2', double(0), ...
    'haMaxBank', double(0), ...
    'haVel', double(0), ...
    'aero_model', double(zeros(70,7)), ...
    'bankFilterConst', double(0), ...
    't_max_heat_rate', double(0), ...
    'max_heat_rate', double(0), ...
    'max_gloading', double(0), ... 
    't_max_gloading', double(0), ...
    'heatRateBand', double(0), ...
    'gLoadingBand', double(0), ...
    'rangeBankBias', double(0), ...
    'vEndQDot_high_cd', double(0), ...
    'vEndQDot_low_cd', double(0), ...
    'K_clsf', double(0), ...
    'K_cdsf', double(0), ...
    'vEndQDot_cd_lim', double(0), ...
    'rootMode', uint8(0) );


%% State data structure
s = struct( ...
    'pcMode', int8(0), ...
    'egMode', int8(0), ...
    'bank_rev_count', uint8(0), ...    
    'cmd_bank_sign', int8(0), ...   
    'cmd_bank', double(0), ...
    't_max', double(0), ...
    'vEndQDot', double(0), ...
    'heatRateDelayTrigger', int8(0), ...
    'heatRateDelayTime', double(0), ...
    'heatRateTriggerTime', double(0), ...
    'azi_error', double(0), ...
    'azi_limit', double(0), ...
    'rangeGo', double(0), ...
    'rangeFlown', double(0), ...
    'xRange', double(0), ...
    'iter', double(0), ...
    'predVal', double(0), ...
    'errVal', double(0), ...
    'flagPred', double(0), ...
    'pertDownrange', double(0), ...
    'dDownrange_dBank', double(0), ...
    'deltaBank', double(0), ...
    'maxDeltaBank', double(0), ...
    'mach', double(0), ...
    'lod_est', double(0), ...
    'clsf', double(0), ...
    'cdsf', double(0), ...
    'cl_est', double(0), ...
    'cd_est', double(0), ...
    'pos_pp_mag', double(0), ...
    'vel_pp_mag', double(0), ...
    'gamma_pp', double(0), ...
    'lat', double(0), ...
    'lon', double(0), ...   
    'lat0', double(0), ...
    'lon0', double(0) );
    

%% Input data structure
i = struct( ... 
    'init_flag',logical(false), ...    
    't', double(0), ... 
    'pos_ii', double(zeros(3,1)), ... 
    'vel_ii', double(zeros(3,1)), ... 
    'sens_accel_ii', double(zeros(3,1)), ... 
    'pos_pp', double(zeros(3,1)), ... 
    'vel_pp', double(zeros(3,1)), ... 
    'alt', double(0) ); 

     
%% Construct combined input data structure
g_dc = struct( ...
    'i', i, ...
    's', s, ...
    'p', p );


end % define_g_dc()