% define_g_msl.m 
%   Define MSL-prime guidance state structure.
%
% Aeroassist Simulation source code
%
% Developed by:
%   Space Systems Design Lab
%   Daniel Guggenheim School of Aerospace Engineering
%   Georgia Institute of Technology
%
% Inputs:
%   none
%   
% Outputs:
%   g_msl - struct(1), multi, empty guidance data structure
%
% Major Revision History:
%   *Created OCT 2011, Z. Putnam

function [g_msl] = define_g_msl()
%#codegen


%% Parameter data structure
  
p = struct( ...   
    'overcontrol', double(0), ...
    'ref_lodv', double(0), ...
    'ref_lodv_vec', double(zeros(6,1)), ...
    'ref_vel', double(zeros(6,1)), ...
    'V_sat', double(0), ...
    'E_flatness', double(0), ...
    'E_g_surface', double(0), ...
    'E_rotation_rate', double(0), ...
    'tof_prm', double(0), ...
    'E_radius_eq', double(0), ...
    'V_rel_switch', double(0), ...
    'E_radius_avg', double(0), ...    
    'V_ha', double(0), ...
    'lat_db_gain', double(0), ...
    'lat_db_min', double(0), ...
    'D_sensible_atm', double(0), ...
    'lod_nom', double(0), ...
    'lodv_lim', double(0), ...
    'pre_bank', double(0), ...
    'tgt_geod_alt', double(0), ...
    'tgt_geod_lat', double(0), ...
    'tgt_lon', double(0), ...
    'ref_trajectory', double(zeros(40,7)) );


%% States data structure

s = struct( ...
    'tgt_overflown', logical(false), ...
    'V_rel_switch_reached', logical(false), ...        
    'phase', uint8(8), ...
    'next_step', uint8(8), ...
    'cmd_bank_sign', int8(0), ...
    'alt_rate', double(0), ...
    'ang_to_tgt', double(0), ...
    'cmd_bank', double(0), ...
    'cmd_lodv', double(0), ...
    'D_mag', double(0), ...
    'lat_ang', double(0), ...
    'lat_db', double(0), ...
    'lod_work', double(0), ...
    'lodv_lim_work', double(0), ...
    'range_final', double(0), ...
    'range_to_tgt', double(0), ...
    'ref_alt_rate', double(0), ...
    'ref_D_mag', double(0), ...
    'ref_f1', double(0), ...
    'ref_f2', double(0), ...
    'ref_f3', double(0), ...
    'ref_range', double(0), ...
    'tgt_transfer_ang', double(0), ...
    'time', double(0), ...
    'time_init', double(0), ...
    'V_mag', double(0), ...
    'V_norm_sq', double(0), ...    
    'U_E_pole', double(zeros(3,1)), ...
    'U_norm_traj', double(zeros(3,1)), ...    
    'U_tgt', double(zeros(3,1)), ...    
    'U_tgt_init', double(zeros(3,1)), ...
    'U_tgt_east', double(zeros(3,1)), ...
    'U_tgt_eq', double(zeros(3,1)), ...
    'V_work', double(zeros(3,1) ));


%% States data structure

i = struct( ...
    'timetag', double(0), ...
    'V_ocg_wrt_Eartho_icrf_ICRF', double(zeros(3,1)), ...
    'V_ocg_wrt_Eartho_itrf_ICRF', double(zeros(3,1)), ...
    'R_ocg_wrt_Eartho_ICRF', double(zeros(3,1)), ...
    'Asens_onb_wrt_Eartho_icrf_OB', double(zeros(3,1)) );
    


%% Construct combined input data structure

g_msl = struct( ...
    'i', i, ...    
    's', s, ...
    'p', p );

end % define_g_msl()
