% define_g_gt.m 
%   Define gravity turn guidance state structure.
%
% Aeroassist Simulation source code
%
% Developed by:
%   Space Systems Design Lab
%   Daniel Guggenheim School of Aerospace Engineering
%   Georgia Institute of Technology
%
% Inputs:
%   none
%   
% Outputs:
%   g_gt - struct(1), multi, guidance data structure
%
% Major Revision History:
%   *Created 11 NOV 2011, Z.R. Putnam
%   *1 AUG 2012, Z.R.Putnam, removed rate limiter parameters

function [g_gt] = define_g_gt()
%#codegen

%% Parameter data structure
p = struct( ...
    'V_mag_min', double(0), ...    
    'tgt_V_mag', double(0), ...
    'tgt_alt',double(0), ...
    'thrust', double(0), ...
    'm_ini', double(0), ...
    'm_ini_mainfuel', double(0), ...
    'r_e', double(0), ...
    'g', double(0), ...
    'g0', double(0), ...
    'isp', double(0), ...   
    't_max', double(0), ...
    'h', double(0), ...
    'fuelmargin', double(0));
%% State data structure
s = struct( ...
    'ignition', logical(false),...
    'throttle', double(1));

%% Input data structure
i = struct( ...
    'R', double(zeros(3,1)), ...
    'V_pf', double(zeros(3,1)) );
     
%% Construct combined input data structure
g_gt = struct( ...
    'i', i, ...
    's', s, ...
    'p', p );


end % define_g_gt()
