% define_ctrl.m 
%   Define flight control data structure.
%
% Aeroassist Simulation source code
%
% Developed by:
%   Space Systems Design Lab
%   Daniel Guggenheim School of Aerospace Engineering
%   Georgia Institute of Technology
%
% Inputs:
%   none
%   
% Outputs:
%   ctrl - struct(1), multi, control data structure
%
% Major Revision History:
%   *Created 17 NOV 2011, Z.R. Putnam
%   *8 FEB 2012, Z.R. Putnam, added angle-of-attack parameters

function ctrl = define_ctrl()
%#codegen

%% Parameter data structure
p = struct( ...
    'aoa_mode', uint8(2), ...
    'bank_mode', uint8(0), ...
    'decel_mode', uint8(0), ...
    'rate', double(0), ...
    'aoa_rate_lim', double(0), ...
    'aoa_accel_lim', double(0), ...    
    'bank_rate_lim', double(0), ...
    'bank_accel_lim', double(0), ...
    'bank_accel_lim1', double(0), ...
    'bank_accel_lim2', double(0), ...
    'bank_accel_dynp1', double(0), ...
    'bank_accel_dynp2', double(0), ...
    'decel_v_box', double(zeros(2,1)));

%% State data structure
s = struct( ...
    'ignition', logical(false), ...
    'throttle', double(1), ...
    'jettison', logical(false), ...
    'not_jettisoned', logical(false), ...
    'deploy_decel', logical(false), ...
    'sc_ratio', double(0), ...        
    't_ini', double(0), ...    
    't_prev', double(0), ...
    't', double(0), ...
    'dt', double(0), ...
    'area_ref', double(0), ...
    'aoa_accel', double(0), ...        
    'aoa_rate', double(0), ...    
    'aoa', double(0), ...   
    'cd', double(0), ...
    'bank_accel', double(0), ...        
    'bank_rate', double(0), ...    
    'bank', double(0) );
     
%% Construct combined input data structure
ctrl = struct( ...
    's', s, ...
    'p', p );

end % define_ctrl()
