% define_nav.m 
%   Define navigation data structure.
%
% Aeroassist Simulation source code
%
% Developed by:
%   Space Systems Design Lab
%   Daniel Guggenheim School of Aerospace Engineering
%   Georgia Institute of Technology
%
% Inputs:
%   none
%   
% Outputs:
%   nav - struct(1), multi, navigation data structure
%
% Major Revision History:
%   *Created 9 AUG 2012, Z.R.Putnam

function nav = define_nav()
%#codegen

p_ecrv = struct( ...
    'P_SS', double(zeros(9,9)), ...  % steady state covariance matrix
    'tau', double(0) ...
);

p_exp = struct( ...
    'P0',double(zeros(9,9)), ...    % initial covariance
    'ercv0', double(zeros(9,1)), ... %initial error
    'tau_r',double(0), ...  % position error time constant
    'tau_v',double(0), ...  % velocity error time constant
    'tau_a',double(0) ...   % accel error time constant
);

p_atm = struct( ...
    'r_e', double(0), ...
    'r_p', double(0), ...
    'omega', double(zeros(3,1)) ...
);


%% Parameter data structure
p = struct( ...
    'mode', uint8(0), ...
    'seed', uint32(0), ...
    'rate', double(0), ...
    'atm', p_atm, ...
    'rva_errs', zeros(9,20000), ... %pre determined rva errors
    'ecrv', p_ecrv, ...
    'n_exp', p_exp ...
);

%% State data structure
s = struct( ...
    'r_pci', double(zeros(3,1)), ...
    'r_pcpf', double(zeros(3,1)), ...
    'v_inrtl_pci', double(zeros(3,1)), ...
    'v_pf_pci', double(zeros(3,1)), ...
    'v_pf_pcpf', double(zeros(3,1)), ...
    'a_sens_pci', double(zeros(3,1)), ...
    'a_sens_pcpf', double(zeros(3,1)), ...
    'r_ii_err', double(zeros(3,1)), ...
    'v_ii_err', double(zeros(3,1)), ...
    'a_ii_err', double(zeros(3,1)), ...
    'lat_gd', double(0), ...
    'lon', double(0), ...
    'alt', double(0), ...
    'dt', double(0), ...
    'sn_ratio', double(0), ...
    't', double(0), ...
    't_ini', double(0), ...
    'nav_ind', double(1), ...
    'ercv', double(zeros(9,1)), ...
    'x_ercv', double(zeros(9,1)), ...
    'rva_error', double(zeros(9,1)) );
     
%% Construct combined input data structure
nav = struct( ...
    's', s, ...
    'p', p );

end % define_nav()
