

function [] = out_stats(out)

% count crashes
nCrashes = length(find(out.haf < out.nom.traj.alt(1)/1000));
nEscapes = length(find(out.haf < 0));

fprintf([ ... 
    'median ha: %4.2f\n' ...
    'mean ha: %4.2f\n' ...
    'std ha: %4.2f\n' ...
    'min ha: %4.2f\n' ...
    'max ha: %4.2f\n' ...
    'impacts: %i\n' ...
    'escapes: %i\n'], ...
    median(out.haf), mean(out.haf), ... 
    std(out.haf), ...
    min(out.haf), ...
    max(out.haf), ...
    nCrashes, ...
    nEscapes);

end