

function [] = out_stats(out)
fprintf([ ... 
    'median ha: %4.2f\n' ...
    'mean ha: %4.2f\n' ...
    'std ha: %4.2f\n' ...
    'median dv: %4.2f\n' ...
    'std dv: %4.2f\n'], ...
    median(out.haf), mean(out.haf), ... 
    std(out.haf), ...
    median(out.dv), std(out.dv));

end