

function [] = out_stats(out, within)

if nargin == 2
    haf = out.haf(find(abs(out.haf) <= prctile(out.haf, within)));
else
    haf = out.haf;
end

nCrashes = length(find(haf < out.traj.alt(1,1)));
nEscapes = length(find(haf < 0));
    
fprintf([ ... 
    'median ha: %4.2f\n' ...
    'std ha: %4.2f\n' ...
    'min ha: %4.2f\n' ...
    'max ha: %4.2f\n' ...
    'impacts: %i\n' ...
    'escapes: %i\n'], ...
    median(haf), ...
    std(haf), ...
    min(haf), ...
    max(haf), ...
    nCrashes, ...
    nEscapes);

% fprintf([ ... 
%     'median ha: %4.2f\n' ...
%     'mean ha: %4.2f\n' ...
%     'std ha: %4.2f\n' ...
%     'min ha: %4.2f\n' ...
%     'max ha: %4.2f\n' ...
%     'impacts: %i\n' ...
%     'escapes: %i\n'], ...
%     median(out.haf), mean(out.haf), ... 
%     std(out.haf), ...
%     min(out.haf), ...
%     max(out.haf), ...
%     nCrashes, ...
%     nEscapes);

end